INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('kml729', 'test', 'mili', 'kml729@naver.com');
INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('alfl729', 'test', 'test', 'test@naver.com');

INSERT INTO QUESTION(ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (1, 1, 'test 문제', 'test문제', CURRENT_TIMESTAMP());
INSERT INTO QUESTION(ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (2, 2, 'test2 문제', 'test2문제', CURRENT_TIMESTAMP());